	<button class="vk-btn" data-key="J">J</button>
	<button class="vk-btn" data-key="K">K</button>
	<button class="vk-btn" data-key="L">L</button>
	<button class="vk-btn" data-key="M">M</button>
	<button class="vk-btn" data-key="N">N</button>
	<button class="vk-btn" data-key="O">O</button>
	<button class="vk-btn" data-key="P">P</button>
	<button class="vk-btn" data-key="Q">Q</button>
	<button class="vk-btn" data-key="R">R</button>
	<button class="vk-btn" data-key="S">S</button>
	<button class="vk-btn" data-key="T">T</button>
	<button class="vk-btn" data-key="U">U</button>
	<button class="vk-btn" data-key="V">V</button>
	<button class="vk-btn" data-key="W">W</button>
	<button class="vk-btn" data-key="X">X</button>
	<button class="vk-btn" data-key="Y">Y</button>
	<button class="vk-btn" data-key="Z">Z</button>

	<button class="vk-btn" data-key="0">0</button>
	<button class="vk-btn" data-key="1">1</button>
	<button class="vk-btn" data-key="2">2</button>
	<button class="vk-btn" data-key="3">3</button>
	<button class="vk-btn" data-key="4">4</button>
	<button class="vk-btn" data-key="5">5</button>
	<button class="vk-btn" data-key="6">6</button>
	<button class="vk-btn" data-key="7">7</button>
	<button class="vk-btn" data-key="8">8</button>
	<button class="vk-btn" data-key="9">9</button>